disabled_rules: # rule identifiers turned on by default to exclude from running
  - function_parameter_count
  - trailing_whitespace
  - trailing_comma
  - type_name
  - xctfail_message

force_cast: warning
force_try:
  severity: warning

included:
  - Kkuk

excluded:
  - Kkuk/Application/AppDelegate.swift
  - Kkuk/Application/SceneDelegate.swift
  - Kkuk/Application/AppTabBarController.swift
  - Kkuk/Resource
  - KkukTests
  - KkukUITests
  
line_length: 160

file_length:
  warning: 500
  error: 1000

type_body_length:
  - 300 # warning
  - 400 # error

cyclomatic_complexity:
  - 10 # only show warning
  - 15 # force error

identifier_name:
  min_length:
    error: 2
  excluded: # excluded via string array
    - id
    - URL
    - uuid
    - GlobalAPIKey 
